# Habilita los íconos y usa un tema "nerd" si tienes una Nerd Font instalada
icons:
  theme: "fancy"
  when: "always"

# =========================================================
# Configuración de colores personalizada para LSDeluxe
# =========================================================
# == Color ==
color:
  # Use a custom color scheme defined in colors.yaml
  theme: custom